name: bld-ci

on: [push, pull_request, workflow_dispatch]

jobs:
  build-project:
    runs-on: ubuntu-latest

    strategy:
     matrix:
       java-version: [ 17, 19 ]

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java-version }}

      - name: Run tests
        run: ./bld download compile test